security:
  basic:
    enabled: false
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: info
    org:
      springframework:
        data:
          jpa: warn
        test: warn
      hibernate:
        engine:
          jdbc: debug
    nl:
      computerhok:
        cruddie: info